// Loads the real NAIGC Nationals 2026 results (public/data/nationals-2026.json,
// generated by scripts/import_nationals.py) into the demo database as a
// completed event — real-scale test data (~1,500 athletes, ~6,700 scores).
import { mutate } from './store';
import type { Athlete, Club, Discipline, Level, Event, Registration, Score } from './types';
import { STATE_REGIONS } from './types';

interface NatJson {
  meta: { name: string; slug: string; generated: string; source: string };
  levels: { id: string; discipline: Discipline; name: string; svMax: number | null; vaults: number; order: number }[];
  clubs: { id: string; name: string; shortName: string }[];
  people: { id: string; f: string; l: string; e: string; g: string; student: boolean; clubId: string }[];
  regs: {
    id: string; athleteId: string; clubId: string; discipline: Discipline; levelId: string;
    category?: string; events: string[]; scores: Record<string, number>;
    places?: Record<string, number>; quals?: Record<string, boolean>;
  }[];
}

export const NATIONALS_MEET_ID = 'meet-natreal26';

// The importer minted new MAG level ids for names that already exist in the
// platform's level table — remap instead of duplicating.
const LEVEL_REMAP: Record<string, string> = {
  'mag-beg': 'mag-dev',
  'mag-int2': 'mag-int',
  'mag-adv2': 'mag-adv',
};

export async function loadNationals(): Promise<{ athletes: number; scores: number }> {
  const res = await fetch(`${import.meta.env.BASE_URL}data/nationals-2026.json`);
  if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
  const data: NatJson = await res.json();

  const lvl = (id: string) => LEVEL_REMAP[id] ?? id;
  const disciplines: Discipline[] = ['WAG', 'MAG', 'TNT'];
  const sessions = disciplines.map((d) => ({
    id: `natreal-${d.toLowerCase()}`,
    name: `${d} Prelims`,
    discipline: d,
    date: d === 'WAG' ? '2026-04-08' : d === 'MAG' ? '2026-04-09' : '2026-04-10',
    time: '09:00',
    levelIds: [] as string[],
    squads: [],
  }));
  const sessionFor = Object.fromEntries(sessions.map((s) => [s.discipline, s]));

  const event: Event = {
    id: NATIONALS_MEET_ID,
    slug: data.meta.slug,
    name: `${data.meta.name} (Real Results)`,
    hostClubId: 'club-1',
    city: 'Pittsburgh', state: 'Pennsylvania', timezone: 'America/New_York',
    startDate: '2026-04-08', endDate: '2026-04-11',
    status: 'complete',
    regOpens: '2026-01-15T12:00', regCloses: '2026-03-15T23:59',
    entryFee: 95, secondDisciplineFee: 45,
    disciplines,
    sessions,
  };

  let scoreCount = 0;
  mutate((db) => {
    // Idempotent: wipe any previous import first.
    db.events = db.events.filter((m) => m.id !== NATIONALS_MEET_ID);
    db.registrations = db.registrations.filter((r) => r.eventId !== NATIONALS_MEET_ID);
    db.scores = db.scores.filter((s) => s.eventId !== NATIONALS_MEET_ID);
    db.clubs = db.clubs.filter((c) => !c.id.startsWith('nc'));
    db.people = db.people.filter((p) => !p.id.startsWith('na'));

    // Levels: add only genuinely new ones.
    for (const L of data.levels) {
      const id = lvl(L.id);
      if (!db.levels.some((x) => x.id === id)) {
        db.levels.push({ id, discipline: L.discipline, name: L.name, svMax: L.svMax, vaults: L.vaults, order: L.order } as Level);
      }
    }

    for (const c of data.clubs) {
      db.clubs.push({
        id: c.id, name: c.name, shortName: c.shortName,
        state: 'Other', region: STATE_REGIONS[c.name] ?? 'Other',
        managerIds: [], email: '', allowClubPay: false, access: 'open',
      } as Club);
    }

    for (const p of data.people) {
      db.people.push({
        id: p.id, kind: 'athlete', roles: { athlete: true, coach: false },
        firstName: p.f, lastName: p.l, email: p.e,
        dob: '', gender: (p.g === 'Female' || p.g === 'Male' ? p.g : 'Other'),
        gradYear: 1900, studentStatus: p.student ? 'Student' : 'Non-Student',
        shirt: '', country: 'United States', state: '', phone: '',
        mainClubId: p.clubId, altClubIds: [], levels: {},
        emergency: { contact: '', relation: '', phone: '' },
        dietary: [], dietaryNotes: '', memberships: [], achievements: [],
      } as Athlete);
    }

    const levelSeen: Record<Discipline, Set<string>> = { WAG: new Set(), MAG: new Set(), TNT: new Set() };
    for (const r of data.regs) {
      const levelId = lvl(r.levelId);
      levelSeen[r.discipline]?.add(levelId);
      const session = sessionFor[r.discipline];
      const reg: Registration = {
        id: r.id, eventId: NATIONALS_MEET_ID,
        athleteId: r.athleteId, clubId: r.clubId,
        discipline: r.discipline, levelId,
        apparatus: r.events, sessionId: session.id,
        category: r.category, quals: r.quals,
      };
      db.registrations.push(reg);
      for (const [ev, finalScore] of Object.entries(r.scores)) {
        scoreCount++;
        db.scores.push({
          id: `${NATIONALS_MEET_ID}|${r.id}|${ev}`,
          eventId: NATIONALS_MEET_ID, sessionId: session.id, regId: r.id, apparatus: ev,
          sv: null, deductions: null, eScore: null, final: finalScore,
          source: 'manual', enteredBy: 'import-nationals-2026', enteredAt: data.meta.generated, flashed: true,
        } as Score);
      }
    }
    for (const s of sessions) {
      const ids = [...levelSeen[s.discipline]];
      const order = (id: string) => db.levels.find((l) => l.id === id)?.order ?? 99;
      s.levelIds = ids.sort((a, b) => order(a) - order(b));
    }
    db.events.push(event);
  });

  return { athletes: data.people.length, scores: scoreCount };
}
