// Neck-ribbon color/style options for sanctioned-event awards, from the A-1 Awards
// catalog (https://www.a-1awards.com/sports-neck-ribbon-gallery). Transcribed from
// the 2026-06-18 feedback doc. Hosts rank their top 3; blank ⇒ default Navy Blue.
// `code` is the A-1 SKU, `name` the display label.
export interface RibbonOption { code: string; name: string }

export const DEFAULT_RIBBON = 'SNR- Navy Blue';

export const RIBBON_OPTIONS: RibbonOption[] = [
  { code: 'NR-1507F', name: 'Beach' },
  { code: 'NR-1507H', name: 'Fall' },
  { code: 'NR-1505N', name: 'Winter' },
  { code: 'NR-1507D', name: 'Princess' },
  { code: 'NR-1508A', name: 'Ninja' },
  { code: 'NR-1507G', name: 'Superhero' },
  { code: 'NR-1506C', name: 'Superhero' },
  { code: 'NR-1506B', name: 'Heart' },
  { code: 'NR-1507B', name: 'Peace' },
  { code: 'NR-1507E', name: 'Circus' },
  { code: 'NR-1506A', name: 'Snowflake' },
  { code: 'NR-1507A', name: 'Flame' },
  { code: 'NR-1507C', name: 'Shamrock' },
  { code: 'NR-1505A', name: 'USA' },
  { code: 'NR-1505L', name: 'Teal' },
  { code: 'NR-1505C', name: 'Red' },
  { code: 'NR-1505G', name: 'Purple' },
  { code: 'NR-1505E', name: 'Black' },
  { code: 'NR-1505B', name: 'Blue' },
  { code: 'NR-1505K', name: 'Green' },
  { code: 'NR-1505J', name: 'Orange' },
  { code: 'NR-1505D', name: 'White' },
  { code: 'NR-1505H', name: 'Yellow' },
  { code: 'NR-1505F', name: 'Pink' },
  { code: 'CH-1', name: 'Gold' },
  { code: 'CH-2', name: 'Silver' },
  { code: 'CH-3', name: 'Bronze' },
  { code: 'NR-1503G', name: 'White' },
  { code: 'NR-1503E', name: 'Red' },
  { code: 'NR-1501', name: 'Rainbow' },
  { code: 'NR-1503F', name: 'Purple' },
  { code: 'NR-1503D', name: 'Pink' },
  { code: 'NR-1503A', name: 'Orange' },
  { code: 'NR-1503C', name: 'Blue' },
  { code: 'NR-1503B', name: 'Green' },
  { code: 'NR-1504P', name: 'Pink Camo' },
  { code: 'NR-1504G', name: 'Green Camo' },
  { code: 'NR-1502D', name: 'Pink' },
  { code: 'NR-1502A', name: 'USA' },
  { code: 'NR-1502M', name: 'Black/Red' },
  { code: 'NR-1502B', name: 'Blue' },
  { code: 'NR-1502F', name: 'Red' },
  { code: 'NR-1502G', name: 'Purple' },
  { code: 'NR-1502L', name: 'Black' },
  { code: 'NR-1502C', name: 'Green' },
  { code: 'NR-1502K', name: 'White' },
  { code: 'NR-1502J', name: 'Orange' },
  { code: 'NR-1502H', name: 'Winter' },
  { code: 'NR-1502E', name: 'Yellow' },
  { code: 'SB-', name: 'Pink' },
  { code: 'SB-', name: 'Green' },
  { code: 'SNR-', name: 'RWB' },
  { code: 'SNR-', name: 'S&S' },
  { code: 'SNR-', name: 'Black' },
  { code: 'SNR-', name: 'Blue' },
  { code: 'SNR-', name: 'Fuchsia' },
  { code: 'SNR-', name: 'Gold' },
  { code: 'SNR-', name: 'Green' },
  { code: 'SNR-', name: 'Hunter Green' },
  { code: 'SNR-', name: 'Red' },
  { code: 'SNR-', name: 'LT Blue' },
  { code: 'SNR-', name: 'Maroon' },
  { code: 'SNR-', name: 'Navy Blue' },
  { code: 'SNR-', name: 'Orange' },
  { code: 'SNR-', name: 'Teal' },
  { code: 'SNR-', name: 'White' },
  { code: 'SNR-', name: 'Pink' },
  { code: 'SNR-', name: 'Purple' },
  { code: 'SNR-', name: 'Yellow' },
  { code: 'NR-1511C', name: 'White/Grey' },
  { code: 'NR-1511M', name: 'Camo' },
  { code: 'NR-1511A', name: 'Blue' },
  { code: 'NR-1511E', name: 'Pink/Purple' },
  { code: 'NR-1511B', name: 'Red' },
  { code: 'NR-1511L', name: 'Red/Black' },
  { code: 'NR-1511F', name: 'Purple' },
  { code: 'NR-1511H', name: 'Orange' },
  { code: 'NR-1511K', name: 'Teal' },
  { code: 'NR-1511J', name: 'Green' },
  { code: 'NR-1511D', name: 'Black/Grey' },
  { code: 'NR-1511G', name: 'Yellow' },
  { code: 'NR-1510C', name: 'Copper' },
  { code: 'NR-1510D', name: 'LT Blue' },
  { code: 'NR-1510F', name: 'Green' },
  { code: 'NR-1510E', name: 'Pink' },
  { code: 'NR-1510G', name: 'Purple' },
  { code: 'NR-1510A', name: 'Gold' },
  { code: 'NR-1510B', name: 'Silver' },
  { code: 'NR-1507K', name: 'Western' },
  { code: 'NR-1507J', name: 'Jungle' },
];
